apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app-deployment
  labels:
    app: frontend-app
spec:
  # Number of pods to replicate.
  replicas: 2

  # Helps to identify which pods to manage. More sophisticated selection rules are possible than just using the template's label.
  selector:
    # Specify a label that can be found in this spec's template for pods.
    matchLabels:
      app: frontend-app-pod

  # Template for pods
  template:
    # Specify info that will help in identifying this template.
    metadata:
      labels:
        app: frontend-app-pod

    # The desired attributes of this templates containers and such.
    spec:
      # A list of containers to create. We could create a Nodejs container, a Postgres container, a Redis container all in one pod.
      containers:
      - name: frontend-app-container
        image: folushooladipo/metagram-frontend-app:latest
        imagePullPolicy: Always
