apiVersion: v1
kind: Service
metadata:
  name: expose-frontend-app
spec:
  type: LoadBalancer
  clusterIP: 10.100.10.1
  selector:
    app: frontend-app-pod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
