apiVersion: v1
kind: Secret
metadata:
  name: env-secret
type: Opaque

data:
  DB_HOST: <DB_HOST_AS_BASE_64_STRING>
  DB_NAME: <DB_NAME_AS_BASE_64_STRING>
  DB_USERNAME: <DB_USERNAME_AS_BASE_64_STRING>
  DB_PASSWORD: <DB_PASSWORD_AS_BASE_64_STRING>
  JWT_SECRET: <JWT_SECRET_AS_BASE_64_STRING>

stringData:
  AWS_MEDIA_BUCKET_NAME: metagram-media-dev
  AWS_REGION: us-east-1

  # TThis value is used by user-service and feed-service to allow cross-origin
  # equests from the specified domain, as that domain is supposed to be an
  # instance of the frontend-app.
  FRONTEND_APP_URL: "http://a5fa51de63e474fb488308cfed6aca45-1897161481.us-east-1.elb.amazonaws.com"

  # This value is used by frontend-app to know where to send API calls to.
  API_DOMAIN: "http://a3b0015dc470a477b8479dae9aa10184-131004894.us-east-1.elb.amazonaws.com"

  # This is used by feed-service to know what endpoint to use to verify the JWT
  # tokens that it gets in requests. If there were other non-user-service
  # services, they would all use this endpoint too to verify tokens.
  AUTH_ENDPOINT: "10.100.50.1:8081/api/v0/users/auth/verify-token"
