apiVersion: v1
kind: Service
metadata:
  name: expose-reverse-proxy
spec:
  type: LoadBalancer
  clusterIP: 10.100.30.1
  selector:
    app: reverse-proxy-pod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
