apiVersion: v1
kind: Service
metadata:
  name: reverse-proxy-service
spec:
  clusterIP: 10.100.40.1
  selector:
    app: reverse-proxy-pod
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
